<?php

use App\Domain\ACL\Models\Permission;
use App\Domain\ACL\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $admin = Role::create([
            'name'       => 'admin',
            'guard_name' => 'web',
            'type'       => 'admin',
            'description' => 'Users in this group can see all fields, edit all fields, and do everything the system offers.',
            'sub_role'   => null,
        ]);
        $manager = Role::create([
            'name'       => 'Manager',
            'guard_name' => 'web',
            'type'       => 'manager',
            'description' => 'This access level grants users access to view some of their direct reports\' employee information.',
            'sub_role'   => '3',
        ]);
        $employee = Role::create([
            'name'       => 'Employee',
            'guard_name' => 'web',
            'type'       => 'employee',
            'description' => 'This access level allows employees to view, edit (with or without approval) some of their own information.',
            'sub_role'   => null,
        ]);


        /*
         * Added All the Permissions to admin.
         */

        $permissions = Permission::all();    //All Permissions Get once For this Seed.
        $roles = Role::all();                 // Getting All Roles

        /*
        * Added All the Permissions to Manager Manually.
        */

        $managerPermissions = [
            'view employee id',
            'view employee firstname',
            'view employee lastname',
            'view employee date_of_birth',
            'view employee gender',
            'view employee nin',
            'view employee marital_status',
            'view employee current_address',
            'view employee permanent_address',
            'view employee city',
            'view employee state',
            'view employee zip_code',
            'view employee country',
            'view employee contact_no',
            'view employee personal_email',
            'view employee official_email',
            'view education institute_name',
            'view education major',
            'view educationtype education_type',
            'view education cgpa',
            'view education date_start',
            'view education date_end',
            'view secondarylanguage name',
            'view visatype visa_type',
            'view employeevisa issue_date',
            'view employeevisa country_id',
            'view employeevisa expire_date',
            'view employeevisa note',
            'view employee joining_date',
            'view employeeemploymentstatus employment_status_id',
            'view employeeemploymentstatus effective_date',
            'view employeeemploymentstatus comments',
            'view employeejob effective_date',
            'view employeejob designation_id',
            'view employeejob report_to',
            'view employeejob department_id',
            'view employeejob division_id',
            'view employeejob location_id',
            'view division name',
            'view department name',
            'view location name',
            'view employeedocument doc_name',
            'view timeofftype time_off_type_name',
            'view policy policy_name',
            'view employee emergency_contact',
            'view employee emergency_contact_relationship',
            'view asset asset_category',
            'view asset asset_description',
            'view asset serial',
            'view asset assign_date',
            'view documenttype document_type_name',
            'view resume and application',
            'view note note',
            'edit note note',
            'view onboarding tab',
            'view offboarding tab',
            'manage performance review',
            'view employee_attendance',
            'edit employee_attendance',
        ];


        /*
        * Added All the Permissions to Employees Manually.
        */
        $employeePermissions = [
            'view employee id',
            'view employee firstname',
            'view employee lastname',
            'view employee date_of_birth',
            'edit employee date_of_birth',
            'edit_with_approval employee date_of_birth',
            'view employee gender',
            'edit employee gender',
            'edit_with_approval employee gender',
            'view employee nin',
            'edit employee nin',
            'edit_with_approval employee nin',
            'view employee marital_status',
            'edit employee marital_status',
            'edit_with_approval employee marital_status',
            'view employee current_address',
            'edit employee current_address',
            'edit_with_approval employee current_address',
            'view employee permanent_address',
            'edit employee permanent_address',
            'edit_with_approval employee permanent_address',
            'view employee city',
            'edit employee city',
            'edit_with_approval employee city ',
            'view employee state',
            'edit employee state',
            'edit_with_approval employee state',
            'view employee zip_code',
            'edit employee zip_code',
            'edit_with_approval employee zip_code',
            'view employee country',
            'edit employee country',
            'edit_with_approval employee country',
            'view employee contact_no',
            'edit employee contact_no',
            'edit_with_approval employee contact_no',
            'view employee personal_email',
            'edit employee personal_email',
            'edit_with_approval employee personal_email',
            'view employee official_email',
            'edit employee official_email',
            'edit_with_approval employee official_email',
            'view education institute_name',
            'edit education institute_name',
            'edit_with_approval education institute_name',
            'view education major',
            'edit education major',
            'edit_with_approval education major',
            'view educationtype education_type',
            'edit educationtype education_type',
            'edit_with_approval educationtype education_type',
            'view education cgpa',
            'edit education cgpa',
            'edit_with_approval education cgpa',
            'view education date_start',
            'edit education date_start',
            'edit_with_approval education date_start',
            'view education date_end',
            'edit education date_end',
            'edit_with_approval education date_end',
            'view secondarylanguage name',
            'edit secondarylanguage name',
            'edit_with_approval secondarylanguage name',
            'view visatype visa_type',
            'view employeevisa issue_date',
            'view employeevisa country_id',
            'view employeevisa expire_date',
            'view employeevisa note',
            'view employee joining_date',
            'view employeeemploymentstatus employment_status_id',
            'view employeeemploymentstatus effective_date',
            'view employeeemploymentstatus comments',
            'view employeejob effective_date',
            'view employeejob designation_id',
            'view employeejob report_to',
            'view employeejob department_id',
            'view employeejob division_id',
            'view employeejob location_id',
            'view division name',
            'view department name',
            'view location name',
            'can request time off',
            'request timeofftype all',
            'view timeofftype time_off_type_name',
            'view policy policy_name',
            'view employee emergency_contact',
            'edit employee emergency_contact',
            'edit_with_approval employee emergency_contact',
            'view employee emergency_contact_relationship',
            'edit employee emergency_contact_relationship',
            'edit_with_approval employee emergency_contact_relationship',
            'view employeebenefit company_payment',
            'view benefitgroup name',
            'view employee benefits history',
            'view employeedependent first_name',
            'edit employeedependent first_name',
            'edit_with_approval employeedependent first_name',
            'view employeedependent middle_name',
            'edit employeedependent middle_name',
            'edit_with_approval employeedependent middle_name',
            'view employeedependent last_name',
            'edit employeedependent last_name',
            'edit_with_approval employeedependent last_name',
            'view employeedependent date_of_birth',
            'edit employeedependent date_of_birth',
            'edit_with_approval employeedependent date_of_birth',
            'view employeedependent SSN',
            'edit employeedependent SSN',
            'edit_with_approval employeedependent SSN',
            'view employeedependent SIN',
            'edit employeedependent SIN',
            'edit_with_approval employeedependent SIN',
            'view employeedependent gender',
            'edit employeedependent gender',
            'edit_with_approval employeedependent gender',
            'view employeedependent relationship',
            'edit employeedependent relationship',
            'edit_with_approval employeedependent relationship',
            'view employeedependent street1',
            'edit employeedependent street1',
            'edit_with_approval employeedependent street1',
            'view employeedependent street2',
            'edit employeedependent street2',
            'edit_with_approval employeedependent street2',
            'view employeedependent city',
            'edit employeedependent city',
            'edit_with_approval employeedependent city',
            'view employeedependent state',
            'edit employeedependent state',
            'edit_with_approval employeedependent state',
            'view employeedependent zip',
            'edit employeedependent zip',
            'edit_with_approval employeedependent zip',
            'view employeedependent country',
            'edit employeedependent country',
            'edit_with_approval employeedependent country',
            'view employeedependent home_phone',
            'edit employeedependent home_phone',
            'edit_with_approval employeedependent home_phone',
            'view employeedependent is_us_citizen',
            'edit employeedependent is_us_citizen',
            'edit_with_approval employeedependent is_us_citizen',
            'view employeedependent is_student',
            'edit employeedependent is_student',
            'edit_with_approval employeedependent is_student',
            'view asset asset_category',
            'edit asset asset_category',
            'edit_with_approval asset asset_category',
            'view asset asset_description',
            'edit asset asset_description',
            'edit_with_approval asset asset_description',
            'view asset serial',
            'edit asset serial',
            'edit_with_approval asset serial',
            'view asset assign_date',
            'edit asset assign_date',
            'edit_with_approval asset assign_date',
            'view employee_attendance',
            'edit employee_attendance',
        ];

        foreach ($permissions as $permission) {
            if ($permission->name == $managerPermissions[array_search($permission->name, $managerPermissions)]) {
                $roles[1]->givePermissionTo(null, $permission);
            }
            if ($permission->name == $employeePermissions[array_search($permission->name, $employeePermissions)]) {
                $roles[2]->givePermissionTo(null, $permission);
            }
        }
    }
}
